In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch

## Example1 -> simple derivative

In [3]:
 x = torch.tensor(3.0 , requires_grad = True) # requires_grad = Flase as default , PyTorch now understands that this var will be used in differentiation further on

In [4]:
y = x**2

In [5]:
x , y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

 tensor(9., grad_fn=<PowBackward0>) -> the grad_fn here tells how this tensor was created so PyTorch knows how to compute gradients later

In [6]:
y.backward()

In [7]:
x.grad

tensor(6.)

## Example 2 -> chain derivative

In [8]:
x = torch.tensor(3.0 , requires_grad = True)

In [9]:
y = x**2

In [10]:
z = torch.sin(y)

In [11]:
x , y , z

(tensor(3., requires_grad=True),
 tensor(9., grad_fn=<PowBackward0>),
 tensor(0.4121, grad_fn=<SinBackward0>))

In [12]:
z.backward()

In [13]:
x.grad # when y.grad -> no opuput because in computation graphs , gradients are calculated arounf root and leaf nodes only and not intermediate  , y  is an intermediate node 

tensor(-5.4668)

## Example3 -> scaler values

In [14]:
import torch 

x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [15]:
#Binary Cross Entropy 
def BCE(prediction , target) :
    epsilon = 1e-8 #to prevent log(0)
    prediction = torch.clamp(prediction , epsilon , 1-epsilon) #torch.clamp-> keeps values withing the safe range , (x , min ,max) -. anything below min - make it min nd anything above max - make it max
    return -(target * torch.log(prediction) + (1-target) * torch.log(1-prediction))

In [16]:
z =  w*x + b
y_pred = torch.sigmoid(z)
loss = BCE(y_pred, y)

In [17]:
loss

tensor(6.7012)

In [18]:
# Derivatives:
# 1. dL/d(y_pred):
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))
# 2. dy_pred/dz:
dy_pred_dz = y_pred * (1 - y_pred)
# 3. dz/dw and dz/db: 
dz_dw = x 
dz_db = 1 

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [19]:
print("Manula Gradients of Loss :")
print(f"w.r.t weight(dw)->{dL_dw}")
print(f"w.r.t weight(db)->{dL_db}")

Manula Gradients of Loss :
w.r.t weight(dw)->6.691762447357178
w.r.t weight(db)->0.998770534992218


In [20]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0,requires_grad = True)
b = torch.tensor(0.1 , requires_grad = True)

In [21]:
x , y , w , b

(tensor(6.7000),
 tensor(0.),
 tensor(1., requires_grad=True),
 tensor(0.1000, requires_grad=True))

In [22]:
z = w*x+b
z

tensor(6.8000, grad_fn=<AddBackward0>)

In [23]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9989, grad_fn=<SigmoidBackward0>)

In [24]:
loss = BCE(y_pred , y)
loss

tensor(6.8011, grad_fn=<NegBackward0>)

In [25]:
loss.backward()

In [26]:
w.grad , b.grad

(tensor(6.6925), tensor(0.9989))

## Example 4 -> Embedded Values

In [27]:
x = torch.tensor([1.0,2.0,3.0],requires_grad = True)
x

tensor([1., 2., 3.], requires_grad=True)

In [28]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [29]:
y.backward()

In [30]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

## Example 5 -> Clearing Grad

In [31]:
x.grad.zero_()

tensor([0., 0., 0.])

## Example 6 -> Disable Gradient Tracking

In [32]:
#option 1 - requires_grad_(False)
x.requires_grad_(False)
x

tensor([1., 2., 3.])

In [33]:
#option 2 - detach()
z = x.detach()
z #z will have same values as x , but it is "detached" from computational graph

tensor([1., 2., 3.])

In [34]:
#option 3 - torch.no_grad()
with torch.no_grad() :
    y = x**2 

In [35]:
y

tensor([1., 4., 9.])