In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch 
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name()}")
else:
    print("GPU not avalable : Using CPU")

GPU is available
Using GPU:Tesla T4


# 1. Creating a Tensor

In [4]:
a = torch.empty(2,3) #shape
a #emply just allocates memory of that certain shape , and does not assign any values , the values in the output are just the default values of those memory places


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3) #random init btw 0,1

tensor([[0.2805, 0.4311, 0.0297],
        [0.8467, 0.9623, 0.0871]])

In [8]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([
        [1,2,3],
        [4,5,6]]
            ) #custom tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.arange(0,10,2) #(start,stop,step)

tensor([0, 2, 4, 6, 8])

In [11]:
torch.linspace(0,10,10) #(start,stop, n) outputs n numbers with equal space in btw , Linearly Spaced

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [12]:
torch.eye(4,5) # diag = 1 , else =0

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [13]:
torch.full((3,3),5) #((shape),value)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# 2. Tensor Shapes

In [14]:
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x) # new emplty tensor of shape like x

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6067527568682134838, 3617017442292347185, 6500999084356546606]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
#all these are creating a new tensor of same shape as x , x is there only for shape reference 
#torch.rand_like(x) -> will through an ERROR because x has int values, rand creates float values , and rand_like dont' just copy shape , but also dtype , so have to specifically mention the dtype change 

In [20]:
torch.rand_like(x , dtype = torch.float32 )

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# 3. Tensor Data Types

In [21]:
x.dtype #find data type

torch.int64

In [22]:
#assign dtype 
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3],dtype = torch.float32)

tensor([1., 2., 3.])

In [24]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# 4. Mathematical Operations

**1. *Scaler opertion***

In [25]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
#add 
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [27]:
#sub
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [28]:
#mul
x * 2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [29]:
#div
x / 2 

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [30]:
#mode
x %2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [31]:
#pow
x ** 2 

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [32]:
#int  div
(x * 100) // 2

tensor([[35., 39.],
        [20., 45.]])

**2. Element Wise Operation**

In [33]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [34]:
a , b

(tensor([[0.9969, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]),
 tensor([[0.5557, 0.9770, 0.4440],
         [0.9478, 0.7445, 0.4892]]))

In [35]:
#add
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [36]:
#sub
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [37]:
#mul
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [38]:
#div
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [39]:
#pow
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [40]:
#mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [41]:
#absolute value 
torch.abs(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [42]:
#negative
torch.neg(x)

tensor([[-0.7118, -0.7876],
        [-0.4183, -0.9014]])

In [43]:
#round
torch.round(x)

tensor([[1., 1.],
        [0., 1.]])

In [44]:
#ceil
torch.ceil(x)

tensor([[1., 1.],
        [1., 1.]])

In [45]:
#floor
torch.floor(x)

tensor([[0., 0.],
        [0., 0.]])

In [46]:
#clamp
torch.clamp(x , min=2,max=3)

tensor([[2., 2.],
        [2., 2.]])

**3. Reduction Operation**

In [47]:
e = torch.randint(size=(2,3),low = 0 , high=10,dtype = torch.float32)

In [48]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [49]:
#total sum
torch.sum(e)

tensor(24.)

In [50]:
#sum along columns
torch.sum(e, dim=0)

tensor([ 8.,  0., 16.])

In [51]:
#sum along rows
torch.sum(e,axis=1)

tensor([15.,  9.])

In [52]:
#mean
torch.mean(e)  #torch.mean(x.float()) if x was int 

tensor(4.)

In [53]:
#median
torch.median(e)

tensor(0.)

In [54]:
#max , min
torch.max(x)


tensor(0.9014)

In [55]:
torch.min(x,axis=1) #along some axis

torch.return_types.min(
values=tensor([0.7118, 0.4183]),
indices=tensor([0, 0]))

In [56]:
#prodcut
torch.prod(e)

tensor(0.)

In [57]:
#std dev
torch.std(e)

tensor(4.4272)

In [58]:
#variance
torch.var(e)

tensor(19.6000)

In [59]:
#argmax
torch.argmax(e) #tells the position , not the val

tensor(5)

In [60]:
#agrmin
torch.argmin(e)

tensor(1)

**4. Matrix Operations**

In [61]:
f = torch.randint(size=(3,3),low=0,high=10)
g = torch.randint(size=(3,3),low=0,high=10)
f , g

(tensor([[5, 7, 3],
         [9, 4, 0],
         [5, 7, 5]]),
 tensor([[9, 9, 7],
         [5, 9, 8],
         [9, 7, 9]]))

In [62]:
#matrix mul
torch.matmul(f,g)

tensor([[107, 129, 118],
        [101, 117,  95],
        [125, 143, 136]])

In [63]:
# dot product
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

torch.dot(vector1, vector2) 

tensor(11)

In [64]:
#transpose
torch.transpose(f,0,1) # 0,1 are dim index 

tensor([[5, 9, 5],
        [7, 4, 7],
        [3, 0, 5]])

In [65]:
h = torch.randint(size=(3,3),low = 0, high=10 , dtype = torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [66]:
#determinant/

torch.det(h) # for det , the dtype of elements in matrix has to be float

tensor(-315.)

In [67]:
#inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

**5. Comparison Operations**

In [68]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low = 0,high=10)
i,j

(tensor([[5, 0, 4],
         [3, 8, 8]]),
 tensor([[3, 3, 5],
         [0, 6, 4]]))

In [69]:
#greater than
i >j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [70]:
# less than
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [71]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [72]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [73]:
# greater than equal to
i >= j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [74]:
# less than equal to

i <= j

tensor([[False,  True,  True],
        [False, False, False]])

**6. Special Functions**

In [75]:
k = torch.randint(size=(2,3),low = 0 , high=10, dtype = torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [76]:
#log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [77]:
#exp
torch.exp(k) #e to the power k

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [78]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [79]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [80]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [81]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

# 5. Inplace Operations

In [82]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [83]:
m,n

(tensor([[0.4920, 0.0748, 0.9605],
         [0.3271, 0.0103, 0.9516]]),
 tensor([[0.2855, 0.2324, 0.9141],
         [0.7668, 0.1659, 0.4393]]))

In [84]:
m.add_(n) #inplace operations saves space

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [85]:
m , n

(tensor([[0.7776, 0.3072, 1.8746],
         [1.0939, 0.1762, 1.3909]]),
 tensor([[0.2855, 0.2324, 0.9141],
         [0.7668, 0.1659, 0.4393]]))

In [86]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [87]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

# 6. Copying a Tensor

In [88]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [89]:
b = a # b refers to the same object in the memory as a
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [90]:
a[0][0] =0

In [91]:
a , b

(tensor([[0.0000, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]]),
 tensor([[0.0000, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]]))

In [92]:
id(a) , id(b) #memory addr (identity) of the object x 

(136690669770288, 136690669770288)

In [93]:
c = a.clone() #different memory reference

In [94]:
a , c

(tensor([[0.0000, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]]),
 tensor([[0.0000, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]]))

In [95]:
a[0][0] = 10

In [96]:
a , c

(tensor([[10.0000,  0.8935,  0.0497],
         [ 0.1780,  0.3011,  0.1893]]),
 tensor([[0.0000, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893]]))

In [97]:
id(a) , id(c)

(136690669770288, 136690669623552)

# 7. Tensor Operations on GPU

In [98]:
torch.cuda.is_available()

True

In [99]:
device = torch.device('cuda')

In [100]:
#creating a new tensro on GPU
torch.rand((2,3),device= device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [101]:
#moving existing tensor on GPU
y = x.to(device) #-> new tensor

In [102]:
y+2 #this is performed on GPU

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]], device='cuda:0')

# 8. Reshaping Tensors

In [103]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [104]:
#reshape
a.reshape(2,2,2,2) #original shape product = new shape product

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [105]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
b = torch.rand(2,3,4)
b #2 blocks , each block has 3 rows and 4 cols

tensor([[[0.9186, 0.2131, 0.3957, 0.6017],
         [0.4234, 0.5224, 0.4175, 0.0340],
         [0.9157, 0.3079, 0.6269, 0.8277]],

        [[0.6594, 0.0887, 0.4890, 0.5887],
         [0.7340, 0.8497, 0.9112, 0.4847],
         [0.9436, 0.3904, 0.2499, 0.3206]]])

In [107]:
#permute
c = b.permute(2,0,1) #(indices of the above shape of tensor) and with the help of indices its like rearrangement of the shape
c

tensor([[[0.9186, 0.4234, 0.9157],
         [0.6594, 0.7340, 0.9436]],

        [[0.2131, 0.5224, 0.3079],
         [0.0887, 0.8497, 0.3904]],

        [[0.3957, 0.4175, 0.6269],
         [0.4890, 0.9112, 0.2499]],

        [[0.6017, 0.0340, 0.8277],
         [0.5887, 0.4847, 0.3206]]])

In [108]:
b.shape , c.shape

(torch.Size([2, 3, 4]), torch.Size([4, 2, 3]))

In [109]:
#unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(1).shape #adds new dim of size 1 at the given index pos

torch.Size([226, 1, 226, 3])

In [110]:
#squeeze
d = torch.rand(1,20)
d.squeeze(0).shape# -> removes dim of size=1

torch.Size([20])

# 9. NumPy and PyTorch

In [111]:
import numpy as np
import pandas as pd

In [112]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [113]:
b = a.numpy() #Tensor to numpy arr
b

array([1, 2, 3])

In [114]:
c = np.array([1,2,3])

In [115]:
d = torch.from_numpy(c) # NumPy Arr -> Tensor
d

tensor([1, 2, 3])